import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen max-h-fit bg-gradient-to-r from-indigo-700 via-purple-900 to-pink-700">
        <Header />
        {children}
      </body>
    </html>
  );
}
